name: Approve PR on /lgtm comment

on:
  issue_comment:
    types: [created]

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/lgtm')
    steps:
      - name: approve the PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
